Repository finncyr/hall, pull requests merged in 2020-01, with the labels that each got.

#8 added reverb to sample callback, added reverb.h
  .project
  Debug/sources.mk
  Release/objects.mk
  Release/sources.mk
  Src/reverb_intr.c
  reverb.h
Labels: enhancement

#12 addded smoothener
  Src/reverb_intr.c
Labels: TODO, enhancement

#13 Reuploading UI concept as requested
  UI_concept_graphics/UI_concept_blank.png
  UI_concept_graphics/UI_concept_checkbox_enabled.png
  UI_concept_graphics/UI_concept_ckeckbox_disabled.png
Labels: documentation
